   <div class="page-header ">
    <h1>Ubicación</h1>
    </div>


    <div class="row-fluid well">
    <div class="span4">
              <h3></h3>
      <address>
        <strong>Botica San Juan</strong><br>
        Calle Sur 15 No. 489<br>
        Orizaba, Ver<br>
        <abbr title="Phone">Tel:</abbr> (272)72 5 42 69    </address>
      <address>
        <strong>PROSSALUD</strong><br>
        <a href="mailto:#">prosalud2012@hotmail.com</a>
      </address>
        </div>
        <div class="span4 ">
        <img src="/img/001.png" alt="fachada" width="325" height="250" />
        </div>
    <div class="span4">
	<iframe width="325" height="250" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com.mx/maps?f=q&amp;source=s_q&amp;hl=es&amp;geocode=&amp;q=sur+15+489&amp;aq=&amp;sll=18.845721,-97.098777&amp;sspn=0.009646,0.021136&amp;ie=UTF8&amp;hq=&amp;hnear=Sur+15+489,+Centro,+Orizaba,+Veracruz-Llave&amp;ll=18.845721,-97.098777&amp;spn=0.009646,0.021136&amp;t=m&amp;z=14&amp;output=embed"></iframe><br /><small><a href="https://maps.google.com.mx/maps?f=q&amp;source=embed&amp;hl=es&amp;geocode=&amp;q=sur+15+489&amp;aq=&amp;sll=18.845721,-97.098777&amp;sspn=0.009646,0.021136&amp;ie=UTF8&amp;hq=&amp;hnear=Sur+15+489,+Centro,+Orizaba,+Veracruz-Llave&amp;ll=18.845721,-97.098777&amp;spn=0.009646,0.021136&amp;t=m&amp;z=14" style="color:#0000FF;text-align:left">Ver mapa más grande</a></small>
	</div>
   	</div>
   