   <div class="page-header ">
    <h1>Ubicación</h1>
    </div>

    
    <div class="row-fluid well">
    <div class="span4">    
	<h2>Botica San Juan</h2>
	<p>Parque Nacional Cañón del Río Blanco,<br> Colonia Centro, <br> CP 94300 <br> Orizaba, VER.</p>
	</div>
	<div class="span4 ">
	<img src="/img/pic01.png" alt="fachada" width="325" height="250" /> 
	</div>
    <div class="span4">
	<iframe width="325" height="250" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com.mx/maps?f=q&amp;source=s_q&amp;hl=es&amp;geocode=&amp;q=sur+15+489&amp;aq=&amp;sll=18.845721,-97.098777&amp;sspn=0.009646,0.021136&amp;ie=UTF8&amp;hq=&amp;hnear=Sur+15+489,+Centro,+Orizaba,+Veracruz-Llave&amp;ll=18.845721,-97.098777&amp;spn=0.009646,0.021136&amp;t=m&amp;z=14&amp;output=embed"></iframe><br /><small><a href="https://maps.google.com.mx/maps?f=q&amp;source=embed&amp;hl=es&amp;geocode=&amp;q=sur+15+489&amp;aq=&amp;sll=18.845721,-97.098777&amp;sspn=0.009646,0.021136&amp;ie=UTF8&amp;hq=&amp;hnear=Sur+15+489,+Centro,+Orizaba,+Veracruz-Llave&amp;ll=18.845721,-97.098777&amp;spn=0.009646,0.021136&amp;t=m&amp;z=14" style="color:#0000FF;text-align:left">Ver mapa más grande</a></small>
	</div>
   	</div>
   
        <div class="row-fluid well">
    
     <div class="span4">    
	<h2>Botica San Juan</h2>
	<p>Parque Nacional Cañón del Río Blanco,<br> Colonia Centro, <br> CP 94300 <br> Orizaba, VER
	</p>
	</div>
	<div class="span4 ">
	<img src="/img/pic01.png" alt="fachada" width="325" height="250" /> 
	</div>
    <div class="span4">
	<iframe width="325" height="250" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com.mx/maps?f=q&amp;source=s_q&amp;hl=es&amp;geocode=&amp;q=sur+15+489&amp;aq=&amp;sll=18.845721,-97.098777&amp;sspn=0.009646,0.021136&amp;ie=UTF8&amp;hq=&amp;hnear=Sur+15+489,+Centro,+Orizaba,+Veracruz-Llave&amp;ll=18.845721,-97.098777&amp;spn=0.009646,0.021136&amp;t=m&amp;z=14&amp;output=embed"></iframe><br /><small><a href="https://maps.google.com.mx/maps?f=q&amp;source=embed&amp;hl=es&amp;geocode=&amp;q=sur+15+489&amp;aq=&amp;sll=18.845721,-97.098777&amp;sspn=0.009646,0.021136&amp;ie=UTF8&amp;hq=&amp;hnear=Sur+15+489,+Centro,+Orizaba,+Veracruz-Llave&amp;ll=18.845721,-97.098777&amp;spn=0.009646,0.021136&amp;t=m&amp;z=14" style="color:#0000FF;text-align:left">Ver mapa más grande</a></small>
	</div>
    
     </div>
 
 


