
<div class="container-fluid">
<div class="row">
<div class="span6 well">
<form class=" form-search">
 <legend>Solicitud de analisis</legend>
          <div class="control-group">
            <label class="control-label" for="focusedInput">Nombre de Solicitante</label>
            <div class="controls">
              <input class="input-xlarge" id="applicant_id" value="" type="text">
              <button type="submit" class="btn btn-success"><i class="icon-plus-sign icon-white"></i> Agregar</button>
            </div>
          </div>
 
          <div class="control-group">
            <label class="control-label" for="inputWarning">Nombre de medico</label>
            <div class="controls">
              <input class="input-xlarge" id="medic_id" type="text">
            </div>
          </div>
          <div class="control-group">
            <label class="control-label" for="selectError">Seleccione el especialidad</label>
            <div class="controls">
              <select id="especialidad">
                <option></option>
                <?php foreach($this->especialidades as $especialidad){ ?>
                  <option value="<?php echo $especialidad->id; ?>"><?php echo $especialidad->name; ?></option>          
                <?php } ?>
              </select>
            </div>
          </div>
            <div class="control-group">
            <label class="control-label" for="selectError">Seleccione el estudio</label>
       		<div class="controls">
            <input class="input-xlarge"  id="estudio_name" value="" type="text" >
            <script type="text/javascript">
              window.customInitFunctions = window.customInitFunctions || [];
              window.customInitFunctions.push(
                function(){

                  var cache = {},
                  lastXhr;

                 
                  $('#estudio_name').autocomplete({
                    minLength: 2,
                    source: function( request, response ) {
                      var term = request.term;
                      if ( term in cache ) {
                        response( cache[ term ] );
                        return;
                      }
                      console.log(request);
                      lastXhr = $.getJSON( "/tests/list-json", {
                        specialty_id: $("#especialidad").val(),
                        name__like : "%"+term + "%"
                      }, function( data, status, xhr ) {
                        cache[ term ] = data;
                        if ( xhr === lastXhr ) {
                          response( data.result );
                        }
                      });
                    },
                    focus: function( event, ui ) {
                      $( "#estudio_name" ).val( ui.item.name );
                      return false;
                    },
                    select: function( event, ui ) {
                      $( "#estudio_name" ).val( ui.item.name );
                      console.log(ui.item.id);
                      return false;
                    }
                  })
                  .data( "autocomplete" )._renderItem = function( ul, item ) {
                    return $( "<li></li>" )
                      .data( "item.autocomplete", item )
                      .append( "<a>" + item.name +"</a>" )
                      .appendTo( ul );
                  };

 
                }
              );
            </script>
            
            </div>
          </div>
          <div class="form-actions">
            <button type="submit" class="btn btn-primary">Guardar</button>
            <button class="btn">Cancel</button>
          </div>
         </form>
</div>
<div class="span6 well"><legend>Catalogo de pruebas</legend>
<table class="table table-striped">
        <thead>
          <tr>
             <th>Descripcion</th>
            <th>Categoria</th>
           </tr>
        </thead>
        <tbody>
          <tr>
             <td>GLUCOSA</td>
            <td></td>
            <td><input type="checkbox"></td>
             
          </tr>
          <tr>
             <td>UREA</td>
            <td></td>
            <td><input type="checkbox"></td>
             
          </tr>
          <tr>
             <td>CREATININA</td>
            <td></td>
            <td><input type="checkbox"></td>
             
          </tr>
        </tbody>
      </table>
      <div class="form-actions">
              <button type="submit" class="btn btn-success"><i class="icon-plus-sign icon-white"></i> Agregar</button>
            <button class="btn">Limpiar</button>
          </div>
</div>
</div>
<div class="row">
<div class="span12 well"><legend>Pruebas a realizar</legend>
<table class="table table-striped">
	<tbody>
		<tr>
			<td>Id</td>
			<td>Descripcion</td>
			<td>Val. Referencia</td>
			<td>Unidad</td>
			<td></td>

		</tr>
		<tr>
			<td>17</td>
			<td>COLOR</td>
			<td>Obscuro</td>
			<td>COLOR</td>
			            <td align="center"><a class="btn btn-danger" href="/register/delete/id/23"><i class="icon-trash icon-white"></i></a></td>
			
		</tr>
		<tr>
			<td>16</td>
			<td>VOLUMEN</td>
			<td>10.75</td>
			<td>mg/dL</td>
			            <td align="center"><a class="btn btn-danger" href="/register/delete/id/23"><i class="icon-trash icon-white"></i></a></td>
			
		
		</tr>
				
		 
	</tbody>
</table>

</div>
</div>
</div>

