<div class="page-header">
<h3>Solicitud de Analisis</h3>

</div>
<div class="container-fluid solicitud-analisis">
<div class="row">
<div class="span6 well">
<form class=" form-search">
 <legend>Datos de registro</legend>
          <div class="control-group">
            <label class="control-label" for="focusedInput">Nombre de Solicitante</label>
            <div class="controls">
              <input class="input-xlarge focused" id="applicant_name" value="" type="text">
              <button type="submit" class="btn btn-success"><i class="icon-plus-sign icon-white"></i> Agregar</button>
            </div>
          </div>
 
          <div class="control-group">
            <label class="control-label" for="inputWarning">Nombre de medico</label>
            <div class="controls">
              <input class="input-xlarge" id="" type="text">
            </div>
          </div>
          <div class="control-group">
            <label class="control-label" for="selectError">Seleccione el especialidad</label>
            <div class="controls">
              <select id="especialidad">
                <option></option>
                <?php foreach($this->especialidades as $especialidad){ ?>
                  <option value="<?php echo $especialidad->id; ?>"><?php echo $especialidad->name; ?></option>
                <?php } ?>
              </select>
            </div>
          </div>
            <div class="control-group">
            <label class="control-label" for="selectError">Seleccione el estudio</label>
          <div class="controls">
            <input class="input-xlarge" id="estudio_name" value="" type="text" >
            <script type="text/javascript">
              window.customInitFunctions = window.customInitFunctions || [];
              window.customInitFunctions.push(
                function(){
                	$("#applicant_name").autocomplete({
                        source: function( request, response ) {
                        $.ajax({
                            url: "/contact/search/",
                            dataType: "json",
                            data: {term: request.term},
                            success: function(data) {
                                        response($.map(data, function(item) {
                                        return {
                                        	 id: item.id,
                                             value: item.value
                                             
                                            };
                                    }));
                                }
                            });
                        },
                        minLength: 2,
                        select: function(event, ui) {
                            $('#applicant_name').val(ui.item.id);                            
                        }
                    });
                  var cache = {},
                  lastXhr;

                  $('#estudio_name').autocomplete({
                    minLength: 2,
                    source: function( request, response ) {
                      var term = request.term;
                      if ( term in cache ) {
                        response( cache[ term ] );
                        return;
                      }
                      console.log(request);
                      lastXhr = $.getJSON( "/tests/list-json", {
                        specialty_id: $("#especialidad").val(),
                        name__like : "%"+term + "%"
                      }, function( data, status, xhr ) {
                        cache[ term ] = data;
                        if ( xhr === lastXhr ) {
                          response( data.result );
                        }
                      });
                    },
                    focus: function( event, ui ) {
                      $( "#estudio_name" ).val( ui.item.name );
                      return false;
                    },
                    select: function( event, ui ) {
                      $( "#estudio_name" ).val( ui.item.name );
                      console.log(ui.item.id);
                      AppPrueba.pruebasController.getBy({"test_id": ui.item.id});
                      return false;
                    }
                  })
                  .data( "autocomplete" )._renderItem = function( ul, item ) {
                    return $( "<li></li>" )
                      .data( "item.autocomplete", item )
                      .append( "<a>" + item.name +"</a>" )
                      .appendTo( ul );
                  };

                }
              );
            </script>
            </div>
          </div>
          <div class="form-actions">
            <button type="submit" class="btn btn-primary">Guardar</button>
            <button class="btn">Cancel</button>
          </div>
         </form>
</div>
<div class="span6 well content-catalogo-prueba"><legend>Catalogo de pruebas</legend>
<script type="text/x-handlebars">
<table class="table table-striped">
  <thead>
  <tr>
    <th>Nombre</th>
    <th>Descripcion</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
    {{#each AppPrueba.pruebasController}}
        {{#view AppPrueba.PruebaListView pruebaBinding="this"}}
            <td>{{prueba.name}}</td>
            <td >{{prueba.description}}
            <td><button class="btn btn-success" {{action SelectedItem}} ><i class="icon-plus-sign icon-white"></i></button></td>
        {{/view}}
    {{/each}}
  </tbody>
</table>
</script>​
</div>
</div>
<div class="row">
<div class="span12 well"><legend>Pruebas a realizar</legend>

<script type="text/x-handlebars">
<table class="table table-striped">
  <thead>
  <tr>
    <th>Nombre</th>
    <th>Val. Referencia</th>
    <th>Unidad</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
    {{#each AppPrueba.pruebasSelectedController}}
        {{#view AppPrueba.PruebaSelectedListView pruebaBinding="this"}}
            <td>{{prueba.name}}</td>
            <td >{{prueba.description}}</td>
            <td >{{prueba.description}}</td>
            <td><button class="btn btn-danger" {{action RemoveItem}} ><i class="icon-trash icon-white"></i></button></td>
        {{/view}}
    {{/each}}
  </tbody>
</table>
</script>​

<!--<table class="table table-striped">
<tbody>
<tr>
<td>Id</td>
<td>Descripcion</td>
<td>Val. Referencia</td>
<td>Unidad</td>
<td></td>

</tr>
<tr>
<td>17</td>
<td>COLOR</td>
<td>Obscuro</td>
<td>COLOR</td>
<td align="center"><a class="btn btn-danger" href="/register/delete/id/23"><i class="icon-trash icon-white"></i></a></td>
</tr>
<tr>
<td>16</td>
<td>VOLUMEN</td>
<td>10.75</td>
<td>mg/dL</td>
<td align="center"><a class="btn btn-danger" href="/register/delete/id/23"><i class="icon-trash icon-white"></i></a></td>
</tr>
</tbody>
</table>-->

</div>
</div>
</div>
<script type="text/javascript">
window.customInitFunctions = window.customInitFunctions || [];
window.customInitFunctions.push(
  function(){
    yepnope.injectJs("/js/libs/ember-0.9.5.min.js");
    yepnope.injectJs("/js/models/Prueba.js");
  }
);


</script>