<div class="container-fluid">
<div class="row">
<div class="span6 well"><legend>Analisis</legend> 
            <div class="input-append customfile">
              </div>
             <?php echo $this->form ?>
</div>
<div class="span6 well"><legend>Estudios</legend>
<!--
<table class="table table-striped">
		<tr>
			<th>Id</th>
			<th>Estudio</th>
			<th>&nbsp;</th>
			<th>&nbsp;</th>
		</tr>
		
		<?php if( count( $this->paginator )) :?>

		<?php foreach( $this->paginator as $estudio) :?>

		<tr>
			<td><?php echo $estudio->id;?></td>
			<td><?php echo $estudio->name;?></td>
			<td><a class="btn btn-info" href="#"><i class="icon-align-justify icon-white"></i> Desplegar</a></td></tr>
		
	
		<?php endforeach;?>
		<?php else : ?>
		<tr>
			<td colspan="5">No hay datos</td>
		</tr>
		
		<?php endif;?>
		
		
		<?php if( count( $this->paginator )):?>
		    <?php echo $this->paginator;?>
		<?php endif;?>
	</table> 

-->
<table class="table table-striped">
	<thead>
		<tr>
			<th>Nombre</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>Citología cervicovaginal</td>
			<td><a class="btn btn-info" href="#"><i
				class="icon-align-justify icon-white"></i> Desplegar</a></td>
		</tr>
		<tr>
			<td>Examen general de orina</td>
			<td><a class="btn btn-info" href="#"><i
				class="icon-align-justify icon-white"></i> Desplegar</a></td>
		</tr>
		<tr>
			<td>Cristalización de moco cervical</td>
			<td><a class="btn btn-info" href="#"><i
				class="icon-align-justify icon-white"></i> Desplegar</a></td>
		</tr>
	</tbody>
</table>

</div>
</div>
<div class="row">
<div class="span12 well"><legend>Pruebas</legend>
	<script type="text/x-handlebars">
		<table class="table table-striped">
			<thead>
				<tr>
					<th>Nombre</th>
					<th>Resultado</th>					
				</tr>
			</thead>
			<tbody>
				{{#each Prosalud.controllers.results.collectionController}}					
					{{#view Prosalud.views.results.ListView resultBinding="this"}}
						<td>{{result.item_name}}</td>
						<td>
						{{#if editing}}
							{{view Prosalud.TextField name="result" placeholder="Introduzca el valor correspondiente" valueBinding="result.result"}}
						{{else}}
							<a  {{action "select"}}>{{#if result.result}}{{result.result}}{{else}}Sin valor{{/if}}</a>
						{{/if}}
						</td>
					{{/view}}

				{{/each}}
			</tbody>
		</table>
	</script>
<script type="text/javascript">
window.customInitFunctions = window.customInitFunctions || [];
window.customInitFunctions.push(function(){
	var analysis = Prosalud.models.Analysis.create({
		id: <?php echo $this->analysis["id"]; ?>, 		
	}),
		query = {
			analysis_id: analysis.get( "id" )
		};

	Prosalud.controllers.results.collectionController.get( "store" ).url = "/results/list-json";

	Prosalud.controllers.results.collectionController.search(query, function(itemCollection){
		//console.log(itemCollection);
	});
});
</script>