<div class="container-fluid">
<div class="row">
<div class="span6 well"><legend>Analisis</legend> 
            <div class="input-append customfile">
              </div>
             <?php echo $this->form ?>
</div>
<div class="span6 well"><legend>Estudios</legend>

<script type="text/x-handlebars">
	<table class="table table-striped">
		<thead>
			<tr>
				<th>Nombre</th>
				<th></th>					
			</tr>
		</thead>
		<tbody>
			{{#each Prosalud.controllers.tests.collectionController}}					
				{{#view Prosalud.views.tests.ListFilterResultView testBinding="this"}}
					<td>{{test.name}}</td>
					<td>
						<a class="btn btn-info" href="#" {{action "filterResult"}}><i class="icon-align-justify icon-white"></i> Filtrar</a>						
					</td>
				{{/view}}
			{{/each}}
		</tbody>
	</table>
</script>

</div>
</div>
<div class="row">
<div class="span12 well"><legend>Pruebas</legend>
	<script type="text/x-handlebars">
		<table class="table table-striped">
			<thead>
				<tr>
					<th>Nombre</th>
					<th>Resultado</th>					
				</tr>
			</thead>
			<tbody>
				{{#each Prosalud.controllers.results.collectionController}}					
					{{#view Prosalud.views.results.ListView resultBinding="this"}}
						<td>{{result.item_name}}</td>
						<td>
						{{#if editing}}
							{{view Prosalud.TextField name="result" placeholder="Introduzca el valor correspondiente" valueBinding="result.result"}}
						{{else}}
							<a  {{action "select"}}>{{#if result.result}}{{result.result}}{{else}}Sin valor{{/if}}</a>
						{{/if}}
						</td>
					{{/view}}

				{{/each}}
			</tbody>
		</table>
	</script>
<script type="text/javascript">
window.customInitFunctions = window.customInitFunctions || [];
window.customInitFunctions.push(function(){
	var analysis = Prosalud.models.Analysis.create({
		id: <?php echo $this->analysis["id"]; ?>, 		
	}),
		query = {
			analysis_id: analysis.get( "id" )
		};

	
	Prosalud.controllers.tests.collectionController.searchByResult(query, function(testCollection){
		console.log(resultCollection);
	});

	Prosalud.controllers.results.collectionController.get( "store" ).url = "/results/list-json";

	Prosalud.controllers.results.collectionController.search(query, function(itemCollection){
		//console.log(itemCollection);
	});

});
</script>
