<?php $auth = Zend_Auth::getInstance(); ?>
<div class="container-fluid">
<div class="row">
<div class="span6 well"><legend>Analisis</legend> 
	 <div class="input-append customfile">
    </div>
    <?php echo $this->form 
    ?>
</div>
<div class="span6 well"><legend>Estudios</legend>

<script type="text/x-handlebars">
	<table class="table table-striped">
		<thead>
			{{#view Prosalud.views.tests.ListFilterResultView}}
				<th>Nombre</th>
				<th><a class="btn btn-info" href="#" {{action "showAll"}}><i class="icon-align-justify icon-white"></i>Todos</a></th>					
			{{/view}}
		</thead>
		<tbody>
			{{#each Prosalud.controllers.tests.collectionController}}					
				{{#view Prosalud.views.tests.ListFilterResultView testBinding="this"}}
					<td>{{test.name}}</td>
					<td>
						<a class="btn btn-info" href="#" {{action "filterResult"}}><i class="icon-align-justify icon-white"></i> Filtrar</a>						
					</td>
				{{/view}}
			{{/each}}
		</tbody>
	</table>
</script>

</div>
</div>
<div class="row">
<div class="span12 well"><legend>Pruebas</legend>
	<script type="text/x-handlebars">
		<table class="table table-striped">
			<thead>
				<tr>
					<th>Nombre</th>
					<th>Referencia</th>					
					<th>Unidad</th>					
					<th>Resultado</th>					
				</tr>
			</thead>
			<tbody>
				{{#each Prosalud.controllers.results.collectionController}}					
					{{#view Prosalud.views.results.ListView resultBinding="this"}}
						<td>{{result.item_name}}</td>
						<td>{{result.ref_val_value}}</td>
						<td>{{result.ref_val_unit}}</td>
						<td>
						{{#if Prosalud.controllers.results.collectionController.viewing}}
							{{#if editing}}
								{{view Prosalud.TextField name="result" placeholder="Introduzca el valor correspondiente" valueBinding="result.result"}}
							{{else}}
							<a  {{action "select"}}>{{#if result.result}}{{result.result}}{{else}}Sin valor{{/if}}</a>
							{{/if}}
						{{else}}
							{{result.result}}	
						{{/if}}
						</td>
					{{/view}}

				{{/each}}
			</tbody>
		</table>
	</script>
<script type="text/javascript">
window.customInitFunctions = window.customInitFunctions || [];
window.customInitFunctions.push(function(){
	var analysis = Prosalud.models.Analysis.create({
		id: <?php echo $this->analysis["id"]; ?>, 		
	}),
		query = {
			analysis_id: analysis.get( "id" )
		};
	Prosalud.controllers.results.collectionController.set( "updating", <?php echo ($auth->getIdentity()->role === 'Paciente' ? 'false' : 'true'); ?>)
	
	Prosalud.controllers.tests.dataController.searchByResult(query, function(testCollection){
		Prosalud.controllers.tests.collectionController.set( "content", testCollection );
	});

	Prosalud.controllers.results.dataController.search(query, function(itemCollection){
		Prosalud.controllers.results.collectionController.set( "content", itemCollection);
	});

});
</script>
</div>
</div>
</div>