
<div class="page-header">
<h3>Listado de Estudios</h3>
</div>
<form class="well form-search" action="/tests/search/page/1"  >
 <input type="text" class="input-xlarge" name="like_name" id="like_name" > 
 
      <select id="specialty_id" name="specialty_id">
                <option></option>
                <?php foreach($this->especialidades as $especialidad){ ?>
                  <option value="<?php echo $especialidad->id; ?>"><?php echo $especialidad->name; ?></option>
                <?php } ?>
              </select>
<button type="submit" class="btn btn-info" id="buscar" name="buscar" ><i
	class="icon-search icon-white"></i> Buscar</button>
<a class="btn btn-success" href="/tests/agregar/"><i
	class="icon-plus-sign icon-white"></i> Agregar</a>
</form>

<table class="table table-striped well" id="main-list">
	<tr>
		<td>Id</td>
		<td>Descripcion</td>
		<td>Especialidad</td>
		<td>Tiempo de proceso</td>
		<td>Monto</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
	</tr>

	<?php if( count( $this->paginator )) :?>

	<?php foreach( $this->paginator as $test) :?>

	<tr>
		<td><?php echo $test->id;?></td>
		<td><a href="/items/index/id/<?php echo $test->id; ?>"><?php echo $test->name; ?></a></td>
		<td><?php echo $test->cname;?></td>
		<td><?php echo $test->process_time . " Dias";?></td>
		<td><?php echo "$ " . $test->amount;?></td>

		<td align="center"><a class="btn btn-success"
			href="/tests/update/id/<?php echo $test->id ?>"><i
			class="icon-pencil icon-white"></i></a></td>
		<td align="center"><a class="btn btn-danger"
			href="/tests/delete/id/<?php echo $test->id ?>"><i
			class="icon-trash icon-white"></i></a></td>
	</tr>


	<?php endforeach;?>
	<?php else : ?>
	<tr>
		<td colspan="3">No hay datos</td>
	</tr>

	<?php endif;?>



</table>
	<?php if( count( $this->paginator )):?>
	<?php echo $this->paginator;?>
	<?php endif;?>

<script type="text/javascript">
window.customInitFunctions = window.customInitFunctions || [];
window.customInitFunctions.push(function(){
	$('#main-list').on('click', 'a.btn-danger', function(e){
		e.preventDefault();
		if(confirm("¿Esta seguro de eliminar el estudio?")){
			window.location = $(this).attr('href');
		};
	});
})

</script>