	<div id="myCarousel" class="carousel slide">
    <!-- Carousel items -->
    <div class="carousel-inner">
    
    <div class="active item">
    <div class="hero-unit" style="background-color: transparent; background-image: url('/img/bg-home.jpg'); background-repeat: no-repeat; background-attachment: scroll;">
		<br><br>
		<h1 style="color: #000;">Registrate</h1> 
		<p style="color: #000;">Registrate y recibe informacion sobre nuestros precios y promociones </p>
		<p><a class="btn btn-warning btn-large btn-primary"  href="/contact/add">Registrate&raquo;</a></p>
		
		</div>
    </div>
    <div class="item">
        <div class="hero-unit" style="background-color: transparent; background-image: url('/img/bg-home.jpg'); background-repeat: no-repeat; background-attachment: scroll;">
		<br><br>
		<h1 style="color: #000;">Registrate</h1> 
		<p style="color: #000;">Registrate y recibe informacion sobre nuestros precios y promociones </p>
		<p><a class="btn btn-warning btn-large btn-primary"  href="/contact/add">Registrate&raquo;</a></p>
		
		</div>
    </div>
    <div class="item">
        <div class="hero-unit" style="background-color: transparent; background-image: url('/img/bg-home.jpg'); background-repeat: no-repeat; background-attachment: scroll;">
		<br><br>
		<h1 style="color: #000;">Registrate</h1> 
		<p style="color: #000;">Registrate y recibe informacion sobre nuestros precios y promociones </p>
		<p><a class="btn btn-warning btn-large btn-primary"  href="/contact/add">Registrate&raquo;</a></p>
		
		</div>
    </div>
    </div>
    <!-- Carousel nav -->
    <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
    <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
    </div>
 
	      <div class="row">
        <div class="span4">
                <div class="well" style=" color: white; background-color: #371B42;<!--#DF01A5  -->" >
          <h2>Quienes Somos</h2>
           <p >Recibe nuestras promociones y paquetes por correo electr&oacute;nico. Suscr&iacute;bete a nuestra lista.  </p>
          <p><a class="btn btn-primary" href="/ubicacion">leer m&aacute;s &raquo;</a></p>
        </div>
        </div>
            <div class="span4">
                <div class="well" style=" color: white; background-color: #371B42;<!-- #58ACFA --> ">
                <h2>Servicios</h2>
           <p >Tenemos el listado m&aacute;s completo de estudios por especialidad y servicios de laboratorio</p>
          <p><a class="btn btn-primary" href="/servicios">leer m&aacute;s &raquo;</a></p>
        </div>
            </div>
        <div class="span4">
                <div class="well" style=" color: white; background-color: #371B42;<!--  #BF00FF;--> ">
          <h2>Historial Clin&iacute;co</h2>
          <p>El Historial cl&iacute;nico es una herramienta b&aacute;sica para conocer los antecedentes de un paciente </p>
          <p><a class="btn btn-primary" href="/auth/login/">Iniciar sesi&oacute;n</a></p>
       </div>
       </div>

      </div>