
<div class="row show-grid">

<div class="span8">
<div class="well">
<h1>Crea tu cuenta de Pros Salud.</h1>
<br>
<p>Servicio al cliente Personal calificado le atenderá para apoyarle con
sus requerimientos de información sobre: tipo de estudios,
características del examen, descripción de la muestra e indicaciones
para el paciente</p>
<h2>Resultados</h2>
<br>
<p>Los resultados son reportados confiable y oportunamente mediante
envío por fax o pueden ser consultados en linea</p>


<div class="alert alert-info">Nuestro servicio de consultoría, está
disponible de lunes a viernes de 7:00 a 20:00 horas, y sábados de 7:00 a
18:00 horas</div>



<div class="alert alert-info">
<p class="ar"><i class="icon-user"></i> Ya tienes una cuenta? <a
	href="/auth/login/">Inicia sesion →</a></p>
</div>

</div>
</div>
<div class="span4 ">

<div class="well form-search">
<h3>Formulario de Registro</h3>
<p>¿Dudas, preguntas, comentarios o sugerencias sobre nuestros
servicios?</p>

<?php echo $this->form; ?>

 
 
</div>
</div>
</div>

