<div class="page-header">
  <h1>Bienvenido al cuadro de mando</h1>
  <p> El panel de control le dará una visión instantánea de lo los principales modulos.</p>
</div> 

<div class="row-fluid">
<div class="span6 alert alert-info">
<h2>Pacientes</h2>
<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus,
tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum
massa justo sit amet risus. Etiam porta sem malesuada magna mollis
euismod. Donec sed odio dui.</p>
<p><a class="btn" href="#">View details &raquo;</a></p>
</div>
<!--/span-->
 
<!--/span-->
<div class="span6 alert alert-info">
<h2>Analisis</h2>
<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus,
tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum
massa justo sit amet risus. Etiam porta sem malesuada magna mollis
euismod. Donec sed odio dui.</p>
<p><a class="btn" href="#">View details &raquo;</a></p>
</div>
<!--/span--></div>
<!--/row-->
<div class="row-fluid">
<div class="span6 alert alert-info">
<h2>Estudios</h2>
<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus,
tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum
massa justo sit amet risus. Etiam porta sem malesuada magna mollis
euismod. Donec sed odio dui.</p>
<p><a class="btn" href="/studies">View details &raquo;</a></p>
</div>
<!--/span-->
<div class="span6 alert alert-info">
<h2>Pruebas</h2>
<p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus,
tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum
massa justo sit amet risus. Etiam porta sem malesuada magna mollis
euismod. Donec sed odio dui.</p>
<p><a class="btn" href="#">View details &raquo;</a></p>
</div>
<!--/span-->
 
<!--/span--></div>
 


