
<div class="page-header">
<h3>Listado de Especialidades</h3>
</div>
<form class="well form-search"><input type="text"
	class="input-medium search-query" placeholder="Nombre">
<button type="submit" class="btn btn-info"><i
	class="icon-search icon-white"></i> Buscar</button>
<a class="btn btn-success" href="/especialidades/add"><i
	class="icon-plus-sign icon-white"></i> Agregar</a></form>
<table class="table table-striped">
	<tr>
		<td>Id</td>
		<td>Descripcion</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
	</tr>

	<?php if( count( $this->paginator )) :?>

	<?php foreach( $this->paginator as $dato) :?>

	<tr>
		<td><?php echo $dato->id;?></td>
		<td><a href="/tests/list/id/<?php echo $dato->id; ?>"><?php echo $dato->name; ?></a></td>

		<td align="center"><a class="btn btn-success"
			href="/especialidades/update/id/<?php echo $dato->id ?>"><i
			class="icon-pencil icon-white"></i></a></td>
		<td align="center"><a class="btn btn-danger"
			href="/especialidades/delete/id/<?php echo $dato->id ?>"><i
			class="icon-trash icon-white"></i></a></td>
	</tr>


	<?php endforeach;?>
	<?php else : ?>
	<tr>
		<td colspan="3">No hay datos</td>
	</tr>

	<?php endif;?>


</table>

	<?php if( count( $this->paginator )):?>
	<?php echo $this->paginator;?>
	<?php endif;?>

