<section id="collapse">
<div class="page-header">
<h1>Listado de estudios por especialidad </h1>
</div>
<div class="row-fluid">

<div class="span12 columns">
<p>Seleccione una especialidad para acceder al listado de estudios:</p>

<div class="accordion" id="accordion2">
<div class="accordion-group">
<div class="accordion-heading">
<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
Biología molecular
</a>
</div>
<div style="height: 0px;" id="collapseOne" class="accordion-body collapse">
<div class="accordion-inner">
<div class="row-fluid">
<div class="span12">
<div class="row-fluid">
<div class="span6">
<ul class="the-icons">
<li><i></i>Análisis de fibrosis quística por pcr</li>
<li><i></i>Análisis x-frágil por sondas dna</li>
<li><i></i>Borrelia burgdorferi dna pcr</li>
<li><i></i>Carga viral de citomegalovirus por pcr en sangre</li>
<li><i></i>Carga viral de epstein-barr por pcr</li>
<li><i></i>Carga viral de hepatitis a por pcr</li>
<li><i></i>Carga viral de hepatitis b por bdna</li>
<li><i></i>Carga viral de hepatitis b por pcr</li>
<li><i></i>Carga viral de hepatitis c por pcr</li>
<li><i></i>Carga viral de hepatitis delta por pcr</li>
<li><i></i>Carga viral de herpes simple 1 y 2 por pcr</li>
<li><i></i>Carga viral de hiv-1 (ultrasensible)</li>
<li><i></i>Carga viral de vih (ultrasensible)</li>
<li><i></i>Carga viral de vih por pcr</li>
<li><i></i>Carga viral para virus de hepatitis c por bdna</li>
<li><i></i>Cariotipo con fotografía</li>
<li><i></i>Cariotipo con intercambio de cromatidas hermanas</li>
<li><i></i>Cariotipo en líquido amniótico</li>
<li><i></i>Cariotipo en producto de aborto</li>
<li><i></i>Cariotipo en sangre</li>
<li><i></i>Cariotipo para inestabilidad cromosómica</li>
<li><i></i>Citogenética de enfermedades oncohematólogicas en sangre periférica</li>
<li><i></i>Citogenética de médula ósea</li>
<li><i></i>Citogenético de enfermedades oncohematólogicas en sangre periférica</li>
<li><i></i>Citogenético de enfermedades oncohematólogicas médula ósea</li>
<li><i></i>Citogenético de médula o sangre en leucemias</li>
<li><i></i>Coronavirus en aspirado bronquial por pcr</li>
<li><i></i>Cuantificación de pp65 del citomegalovirus por pcr</li>
<li><i></i>Cultivo mixto de linfocitos</li>
<li><i></i>Det. por pcr de antigeno temprano y tardio de veb</li>
<li><i></i>Deteccion de aspergillus por pcr</li>
<li><i></i>Detección de c. trachomatis y n. gonorrhoeae</li>
<li><i></i>Detección de candida albicans por pcr</li>
<li><i></i>Deteccion de cisticerco por pcr</li>
<li><i></i>Detección de citomegalovirus por pcr en sangre</li>
<li><i></i>Detección de coccidioides por pcr en líquido cefalorraquídeo</li>
<li><i></i>Detección de cryptococcus por pcr en líquido cefalorraquídeo</li>
<li><i></i>Detección de distrofia muscular de duchenne</li>
<li><i></i>Detección de echovirus en lcr por pcr</li>
<li><i></i>Detección de hepatitis b por pcr en suero</li>
<li><i></i>Detección de herpes simple 1 y 2 por pcr en sangre</li>
<li><i></i>Detección de herpes virus tipo 6 por pcr</li>
<li><i></i>Detección de hiv-1 por pcr</li>
<li><i></i>Detección de hiv-2 por pcr</li>

</ul>
</div>
<div class="span6">
<ul class="the-icons">
<li><i></i>Detección de hla-dr</li>
<li><i></i>Deteccion de mycobacterium leprae</li>
<li><i></i>Detección de mycoplasma pneumoniae por pcr asp. bronquial</li>
<li><i></i>Detección de parvovirus b-19 por pcr</li>
<li><i></i>Detección de poliomavirus bk por pcr</li>
<li><i></i>Detección de poliomavirus jc por pcr en l.c.r.</li>
<li><i></i>Detección de resistencia a medicamentos para hbv</li>

<li><i></i>Detección de rubeola en lcr por pcr</li>
<li><i></i>Detección de toxoplasma por pcr en sangre</li>
<li><i></i>Detección de virus de hepatitis c por pcr</li>
<li><i></i>Detección de virus de polio en lcr por pcr</li>
<li><i></i>Deteccion de vph en pacientes masculinos</li>
<li><i></i>Detección del virus de la sarampion por pcr</li>
<li><i></i>Deteccion del virus epstein-barr por pcr en sangre</li>
<li><i></i>Dx. de distrofia muscular facioescapulohumeral</li>
<li><i></i>Enterovirus por pcr en lcr</li>
<li><i></i>Exclusión de paternidad en sangre huella adn</li>
<li><i></i>Fish para diferentes patologías</li>
<li><i></i>Genotipo de apolipoproteina e</li>
<li><i></i>Genotipo de hbv</li>
<li><i></i>Genotipo de papiloma humano (vph) por pcr</li>
<li><i></i>Genotipo de papiloma humano por pcr pac. femenino</li>
<li><i></i>Genotipo de papiloma humano por pcr pac. masculino</li>
<li><i></i>Genotipo del gen jak2 para policitemia vera</li>
<li><i></i>Genotipo para hepatitis c</li>
<li><i></i>Genotipo vih-1</li>
<li><i></i>Hemocromatosis hereditaria por pcr</li>
<li><i></i>Histoplasma capsulatum por pcr</li>
<li><i></i>Hiv-1 genotipo</li>
<li><i></i>Huella de adn (individual)</li>
<li><i></i>Marcador tumoral pml/rar alfa por pcr</li>
<li><i></i>Metil tetra-hidrofolato reductasa (mthfr)</li>
<li><i></i>Metil tetra-hidrofolato reductasa(mthfr)</li>
<li><i></i>Mycobacterium tuberculosis por pcr liq. bronquial</li>
<li><i></i>Mycobacterium tuberculosis por pcr en lcr</li>
<li><i></i>Mycobacterium tuberculosis por pcr en orina</li>
<li><i></i>Mycobacterium tuberculosis por pcr expectoración</li>
<li><i></i>Prueba confirmatoria para influenza a h1n1 por pcr</li>
<li><i></i>Prueba cruzada (ac citotoxicos)</li>
<li><i></i>Virus de papiloma humano (vph) por pcr</li>
<li><i></i>Virus de papiloma humano (vph)-captura de híbridos</li>
<li><i></i>Virus de papiloma humano pcr pac. masculino uretral</li>
<li><i></i>Virus de papiloma humano por ch pac. femenino</li>
<li><i></i>Virus de papiloma humano por pcr pac. femenino</li>

</ul>
</div>
</div>
</div>
</div>									
</div>
</div>
</div>
<div class="accordion-group">
<div class="accordion-heading">
<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
Bioquímica
</a>
</div>
<div style="height: 0px;" id="collapseTwo" class="accordion-body collapse">
<div class="accordion-inner">
<div class="row-fluid">
<div class="span12">
<div class="row-fluid">
<div class="span6">
<ul class="the-icons">
<li><i></i>Análisis de fibrosis quística por pcr</li>
<li><i></i>Análisis x-frágil por sondas dna</li>
<li><i></i>Borrelia burgdorferi dna pcr</li>
<li><i></i>Carga viral de citomegalovirus por pcr en sangre</li>
<li><i></i>Carga viral de epstein-barr por pcr</li>
<li><i></i>Carga viral de hepatitis a por pcr</li>
<li><i></i>Carga viral de hepatitis b por bdna</li>
<li><i></i>Carga viral de hepatitis b por pcr</li>
<li><i></i>Carga viral de hepatitis c por pcr</li>
<li><i></i>Carga viral de hepatitis delta por pcr</li>
<li><i></i>Carga viral de herpes simple 1 y 2 por pcr</li>
<li><i></i>Carga viral de hiv-1 (ultrasensible)</li>
<li><i></i>Carga viral de vih (ultrasensible)</li>
<li><i></i>Carga viral de vih por pcr</li>
<li><i></i>Carga viral para virus de hepatitis c por bdna</li>
<li><i></i>Cariotipo con fotografía</li>
<li><i></i>Cariotipo con intercambio de cromatidas hermanas</li>
<li><i></i>Cariotipo en líquido amniótico</li>
<li><i></i>Cariotipo en producto de aborto</li>
<li><i></i>Cariotipo en sangre</li>
<li><i></i>Cariotipo para inestabilidad cromosómica</li>
<li><i></i>Citogenética de enfermedades oncohematólogicas en sangre periférica</li>
<li><i></i>Citogenética de médula ósea</li>
<li><i></i>Citogenético de enfermedades oncohematólogicas en sangre periférica</li>
<li><i></i>Citogenético de enfermedades oncohematólogicas médula ósea</li>
<li><i></i>Citogenético de médula o sangre en leucemias</li>
<li><i></i>Coronavirus en aspirado bronquial por pcr</li>
<li><i></i>Cuantificación de pp65 del citomegalovirus por pcr</li>
<li><i></i>Cultivo mixto de linfocitos</li>
<li><i></i>Det. por pcr de antigeno temprano y tardio de veb</li>
<li><i></i>Deteccion de aspergillus por pcr</li>
<li><i></i>Detección de c. trachomatis y n. gonorrhoeae</li>
<li><i></i>Detección de candida albicans por pcr</li>
<li><i></i>Deteccion de cisticerco por pcr</li>
<li><i></i>Detección de citomegalovirus por pcr en sangre</li>
<li><i></i>Detección de coccidioides por pcr en líquido cefalorraquídeo</li>
<li><i></i>Detección de cryptococcus por pcr en líquido cefalorraquídeo</li>
<li><i></i>Detección de distrofia muscular de duchenne</li>
<li><i></i>Detección de echovirus en lcr por pcr</li>
<li><i></i>Detección de hepatitis b por pcr en suero</li>
<li><i></i>Detección de herpes simple 1 y 2 por pcr en sangre</li>
<li><i></i>Detección de herpes virus tipo 6 por pcr</li>
<li><i></i>Detección de hiv-1 por pcr</li>
<li><i></i>Detección de hiv-2 por pcr</li>

</ul>
</div>
<div class="span6">
<ul class="the-icons">
<li><i></i>Detección de hla-dr</li>
<li><i></i>Deteccion de mycobacterium leprae</li>
<li><i></i>Detección de mycoplasma pneumoniae por pcr asp. bronquial</li>
<li><i></i>Detección de parvovirus b-19 por pcr</li>
<li><i></i>Detección de poliomavirus bk por pcr</li>
<li><i></i>Detección de poliomavirus jc por pcr en l.c.r.</li>
<li><i></i>Detección de resistencia a medicamentos para hbv</li>

<li><i></i>Detección de rubeola en lcr por pcr</li>
<li><i></i>Detección de toxoplasma por pcr en sangre</li>
<li><i></i>Detección de virus de hepatitis c por pcr</li>
<li><i></i>Detección de virus de polio en lcr por pcr</li>
<li><i></i>Deteccion de vph en pacientes masculinos</li>
<li><i></i>Detección del virus de la sarampion por pcr</li>
<li><i></i>Deteccion del virus epstein-barr por pcr en sangre</li>
<li><i></i>Dx. de distrofia muscular facioescapulohumeral</li>
<li><i></i>Enterovirus por pcr en lcr</li>
<li><i></i>Exclusión de paternidad en sangre huella adn</li>
<li><i></i>Fish para diferentes patologías</li>
<li><i></i>Genotipo de apolipoproteina e</li>
<li><i></i>Genotipo de hbv</li>
<li><i></i>Genotipo de papiloma humano (vph) por pcr</li>
<li><i></i>Genotipo de papiloma humano por pcr pac. femenino</li>
<li><i></i>Genotipo de papiloma humano por pcr pac. masculino</li>
<li><i></i>Genotipo del gen jak2 para policitemia vera</li>
<li><i></i>Genotipo para hepatitis c</li>
<li><i></i>Genotipo vih-1</li>
<li><i></i>Hemocromatosis hereditaria por pcr</li>
<li><i></i>Histoplasma capsulatum por pcr</li>
<li><i></i>Hiv-1 genotipo</li>
<li><i></i>Huella de adn (individual)</li>
<li><i></i>Marcador tumoral pml/rar alfa por pcr</li>
<li><i></i>Metil tetra-hidrofolato reductasa (mthfr)</li>
<li><i></i>Metil tetra-hidrofolato reductasa(mthfr)</li>
<li><i></i>Mycobacterium tuberculosis por pcr liq. bronquial</li>
<li><i></i>Mycobacterium tuberculosis por pcr en lcr</li>
<li><i></i>Mycobacterium tuberculosis por pcr en orina</li>
<li><i></i>Mycobacterium tuberculosis por pcr expectoración</li>
<li><i></i>Prueba confirmatoria para influenza a h1n1 por pcr</li>
<li><i></i>Prueba cruzada (ac citotoxicos)</li>
<li><i></i>Virus de papiloma humano (vph) por pcr</li>
<li><i></i>Virus de papiloma humano (vph)-captura de híbridos</li>
<li><i></i>Virus de papiloma humano pcr pac. masculino uretral</li>
<li><i></i>Virus de papiloma humano por ch pac. femenino</li>
<li><i></i>Virus de papiloma humano por pcr pac. femenino</li>

</ul>
</div>
</div>
</div>
</div>						</div>
			</div>
			</div>
			<div class="accordion-group">
			<div class="accordion-heading">
				<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseThree">
				Citología
				</a>
			</div>
			<div style="height: 0px;" id="collapseThree" class="accordion-body collapse">
				<div class="accordion-inner">
<div class="row-fluid">
<div class="span12">
<div class="row-fluid">
<div class="span6">
<ul class="the-icons">
<li><i></i>Análisis de fibrosis quística por pcr</li>
<li><i></i>Análisis x-frágil por sondas dna</li>
<li><i></i>Borrelia burgdorferi dna pcr</li>
<li><i></i>Carga viral de citomegalovirus por pcr en sangre</li>
<li><i></i>Carga viral de epstein-barr por pcr</li>
<li><i></i>Carga viral de hepatitis a por pcr</li>
<li><i></i>Carga viral de hepatitis b por bdna</li>
<li><i></i>Carga viral de hepatitis b por pcr</li>
<li><i></i>Carga viral de hepatitis c por pcr</li>
<li><i></i>Carga viral de hepatitis delta por pcr</li>
<li><i></i>Carga viral de herpes simple 1 y 2 por pcr</li>
<li><i></i>Carga viral de hiv-1 (ultrasensible)</li>
<li><i></i>Carga viral de vih (ultrasensible)</li>
<li><i></i>Carga viral de vih por pcr</li>
<li><i></i>Carga viral para virus de hepatitis c por bdna</li>
<li><i></i>Cariotipo con fotografía</li>
<li><i></i>Cariotipo con intercambio de cromatidas hermanas</li>
<li><i></i>Cariotipo en líquido amniótico</li>
<li><i></i>Cariotipo en producto de aborto</li>
<li><i></i>Cariotipo en sangre</li>
<li><i></i>Cariotipo para inestabilidad cromosómica</li>
<li><i></i>Citogenética de enfermedades oncohematólogicas en sangre periférica</li>
<li><i></i>Citogenética de médula ósea</li>
<li><i></i>Citogenético de enfermedades oncohematólogicas en sangre periférica</li>
<li><i></i>Citogenético de enfermedades oncohematólogicas médula ósea</li>
<li><i></i>Citogenético de médula o sangre en leucemias</li>
<li><i></i>Coronavirus en aspirado bronquial por pcr</li>
<li><i></i>Cuantificación de pp65 del citomegalovirus por pcr</li>
<li><i></i>Cultivo mixto de linfocitos</li>
<li><i></i>Det. por pcr de antigeno temprano y tardio de veb</li>
<li><i></i>Deteccion de aspergillus por pcr</li>
<li><i></i>Detección de c. trachomatis y n. gonorrhoeae</li>
<li><i></i>Detección de candida albicans por pcr</li>
<li><i></i>Deteccion de cisticerco por pcr</li>
<li><i></i>Detección de citomegalovirus por pcr en sangre</li>
<li><i></i>Detección de coccidioides por pcr en líquido cefalorraquídeo</li>
<li><i></i>Detección de cryptococcus por pcr en líquido cefalorraquídeo</li>
<li><i></i>Detección de distrofia muscular de duchenne</li>
<li><i></i>Detección de echovirus en lcr por pcr</li>
<li><i></i>Detección de hepatitis b por pcr en suero</li>
<li><i></i>Detección de herpes simple 1 y 2 por pcr en sangre</li>
<li><i></i>Detección de herpes virus tipo 6 por pcr</li>
<li><i></i>Detección de hiv-1 por pcr</li>
<li><i></i>Detección de hiv-2 por pcr</li>

</ul>
</div>
<div class="span6">
<ul class="the-icons">
<li><i></i>Detección de hla-dr</li>
<li><i></i>Deteccion de mycobacterium leprae</li>
<li><i></i>Detección de mycoplasma pneumoniae por pcr asp. bronquial</li>
<li><i></i>Detección de parvovirus b-19 por pcr</li>
<li><i></i>Detección de poliomavirus bk por pcr</li>
<li><i></i>Detección de poliomavirus jc por pcr en l.c.r.</li>
<li><i></i>Detección de resistencia a medicamentos para hbv</li>

<li><i></i>Detección de rubeola en lcr por pcr</li>
<li><i></i>Detección de toxoplasma por pcr en sangre</li>
<li><i></i>Detección de virus de hepatitis c por pcr</li>
<li><i></i>Detección de virus de polio en lcr por pcr</li>
<li><i></i>Deteccion de vph en pacientes masculinos</li>
<li><i></i>Detección del virus de la sarampion por pcr</li>
<li><i></i>Deteccion del virus epstein-barr por pcr en sangre</li>
<li><i></i>Dx. de distrofia muscular facioescapulohumeral</li>
<li><i></i>Enterovirus por pcr en lcr</li>
<li><i></i>Exclusión de paternidad en sangre huella adn</li>
<li><i></i>Fish para diferentes patologías</li>
<li><i></i>Genotipo de apolipoproteina e</li>
<li><i></i>Genotipo de hbv</li>
<li><i></i>Genotipo de papiloma humano (vph) por pcr</li>
<li><i></i>Genotipo de papiloma humano por pcr pac. femenino</li>
<li><i></i>Genotipo de papiloma humano por pcr pac. masculino</li>
<li><i></i>Genotipo del gen jak2 para policitemia vera</li>
<li><i></i>Genotipo para hepatitis c</li>
<li><i></i>Genotipo vih-1</li>
<li><i></i>Hemocromatosis hereditaria por pcr</li>
<li><i></i>Histoplasma capsulatum por pcr</li>
<li><i></i>Hiv-1 genotipo</li>
<li><i></i>Huella de adn (individual)</li>
<li><i></i>Marcador tumoral pml/rar alfa por pcr</li>
<li><i></i>Metil tetra-hidrofolato reductasa (mthfr)</li>
<li><i></i>Metil tetra-hidrofolato reductasa(mthfr)</li>
<li><i></i>Mycobacterium tuberculosis por pcr liq. bronquial</li>
<li><i></i>Mycobacterium tuberculosis por pcr en lcr</li>
<li><i></i>Mycobacterium tuberculosis por pcr en orina</li>
<li><i></i>Mycobacterium tuberculosis por pcr expectoración</li>
<li><i></i>Prueba confirmatoria para influenza a h1n1 por pcr</li>
<li><i></i>Prueba cruzada (ac citotoxicos)</li>
<li><i></i>Virus de papiloma humano (vph) por pcr</li>
<li><i></i>Virus de papiloma humano (vph)-captura de híbridos</li>
<li><i></i>Virus de papiloma humano pcr pac. masculino uretral</li>
<li><i></i>Virus de papiloma humano por ch pac. femenino</li>
<li><i></i>Virus de papiloma humano por pcr pac. femenino</li>

</ul>
</div>
</div>
</div>
</div>		</div>
</div>
</div>
</div>


 </div>
</div>
</section>
