
<div class="page-header">
<h3>Valores de Refrencia</h3>
</div>
<form class="well form-search"><input type="text"
	class="input-medium search-query" placeholder="Nombre de prueba">
<button type="submit" class="btn btn-info"><i
	class="icon-search icon-white"></i> Buscar</button>
<a class="btn btn-success" href="/references/add/"><i
	class="icon-plus-sign icon-white"></i> Agregar</a></form>
<table class="table table-striped well" id="main-list">
	<tr>
		<th>Id</th>
		<th>Nombre</th>
		<th>Valor de referencia</th>
		<th>Unidad</th>
		<th>Genero</th>
 		<th>Tipo de Prueba</th>
		<th>&nbsp;</th>
		<th>&nbsp;</th>
	</tr>

	<?php if( count( $this->paginator )) :?>

	<?php foreach( $this->paginator as $reference) :?>

	<tr>
		<td><?php echo $reference->id;?></td>
		<td><?php echo $reference->name;?></td>
		<td><?php echo $reference->value;?></td>
		<td><?php echo $reference->unit;?></td>
		<td><?php echo $reference->gender;?></td>
 		<td><?php echo $reference->type;?></td>

		<td align="center"><a class="btn btn-success"
			href="/references/update/id/<?php echo $reference->id ?>"><i
			class="icon-pencil icon-white"></i></a></td>
		<td align="center"><a class="btn btn-danger"
			href="/references/delete/id/<?php echo $reference->id ?>"><i
			class="icon-trash icon-white"></i></a></td>
	</tr>


	<?php endforeach;?>
	<?php else : ?>
	<tr>
		<td colspan="5">No hay datos</td>
	</tr>

	<?php endif;?>
	
</table>
<?php if( count( $this->paginator )):?>
	<?php echo $this->paginator;?>
	<?php endif;?>
<script type="text/javascript">
window.customInitFunctions = window.customInitFunctions || [];
window.customInitFunctions.push(function(){
	$('#main-list').on('click', 'a.btn-danger', function(e){
		e.preventDefault();
		if(confirm("¿Esta seguro de eliminar la referencia?")){
			window.location = $(this).attr('href');
		};
	});
})

</script>