<?php echo $this->doctype() ?>
<html lang="en">
<head>
<meta charset="utf-8">
<link rel="shortcut icon" href="/img/favi.ico" />
<title>Pros Salud</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="">
<meta name="author" content="">

<!-- Le styles -->
<link href="/css/bootstrap.css" rel="stylesheet">

<style type="text/css">
body {
	padding-top: 60px;
	padding-bottom: 40px;
}
</style>
<link href="/css/bootstrap-responsive.css" rel="stylesheet">


</head>

<body>
<div class="navbar navbar-fixed-top">
<div class="navbar-inner">
<div class="container">
 
	<a class="brand" href="/index">Pros Salud</a>

<div class="nav-collapse">
<ul class="nav">


	<?php
	$auth = Zend_Auth::getInstance();
	if ( $auth->hasIdentity()) :
	?>
	<li><a href="/dashboard">Cuadro de mando</a></li>
 	<li><a href="/auth/logout">Logout</a></li>
	<?php else: ?>
	<li><a href="/servicios">Servicios</a></li>
	<li ><a href="/especialidades/public">Especialidades</a> 	</li>
	<li><a href="/ubicacion">Ubicación</a></li>
	<li><a href="/contact/add">Registro</a></li>
	<li><a href="/auth/login/">Login</a></li>
	<?php endif;?>
</ul>
</div>
<!--/.nav-collapse --></div>
</div>
</div>

<div class="container ">
 
 
	<?php echo $this->layout()->content ?>
 
<hr>

<footer>
<p align="justify">&copy; Prossalud 2012</p>
</footer></div>
<!-- /container -->

<script src="/js/jquery.js"></script>
<script src="/js/bootstrap.js"></script>
<script src="/js/custom.js"></script>
<script src="/js/bootstrap-transition.js"></script>
<script src="/js/bootstrap-alert.js"></script>
<script src="/js/bootstrap-modal.js"></script>
<script src="/js/bootstrap-dropdown.js"></script>
<script src="/js/bootstrap-scrollspy.js"></script>
<script src="/js/bootstrap-tab.js"></script>
<script src="/js/bootstrap-tooltip.js"></script>
<script src="/js/bootstrap-popover.js"></script>
<script src="/js/bootstrap-button.js"></script>
<script src="/js/bootstrap-collapse.js"></script>
<script src="/js/bootstrap-carousel.js"></script>
<script src="/js/bootstrap-typeahead.js"></script>
</body>
</html>
