<div class="page-header">
<h3>Listado de Pruebas</h3>
</div>
<form class="well form-search"><input type="text"
	class="input-medium search-query" placeholder="Nombre"> <select
	id="select01">
	<option></option>
	<option>..</option>
	<option>..</option>
	<option>..</option>
</select>
<button type="submit" class="btn btn-info"><i
	class="icon-search icon-white"></i> Buscar</button>
<a class="btn btn-success" href="/items/agregar/"><i
	class="icon-plus-sign icon-white"></i> Agregar</a></form>

<table class="table table-striped well" id="main-list">
	<tr>
		<td>Id</td>	
		<td>nombre</td>
		<td>Estudio</td>
 		<td>Referencia</td>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
	</tr>

	<?php if( count( $this->paginator )) :?>

	<?php foreach( $this->paginator as $item) :?>

	<tr>
		<td><?php echo $item->id;?></td>
		<td><?php echo $item->name;?></td>
		<td><?php echo $item->cname;?></td>
 		<td><?php if($item->reference_id):?>
		<a href="/references/index/id/<?php echo $item->reference_id; ?>">Referencia </a>
		<?php else: ?> 
		Sin Referencia
		<?php endif; ?>
		</td>

		<td align="center"><a class="btn btn-success"
			href="/items/update/id/<?php echo $item->id ?>"><i
			class="icon-pencil icon-white"></i></a></td>
		<td align="center"><a class="btn btn-danger"
			href="/items/delete/id/<?php echo $item->id ?>"><i
			class="icon-trash icon-white"></i></a></td>
	</tr>


	<?php endforeach;?>
	<?php else : ?>
	<tr>
		<td colspan="7">No hay datos</td>
	</tr>

	<?php endif;?>


	
</table>
<?php if( count( $this->paginator )):?>
	<?php echo $this->paginator;?>
	<?php endif;?>
<script type="text/javascript">
window.customInitFunctions = window.customInitFunctions || [];
window.customInitFunctions.push(function(){
	$('#main-list').on('click', 'a.btn-danger', function(e){
		e.preventDefault();
		if(confirm("¿Esta seguro de eliminar la prueba?")){
			window.location = $(this).attr('href');
		};
	});
})

</script>