 
<a href="/items/agregar/">Agregar</a>
	   		  <div class="page-header">
    <h2>Listado de pruebas </h2>
  </div>
	
	<table  class="table table-striped">
		<tr>
			<td>Id</td>
			<td>nombre</td>
			<td>Estudio</td>
			<td>descipcions</td>
			<td>Fecha de creacion</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>
		
		<?php if( count( $this->paginator )) :?>
		
		<?php foreach( $this->paginator as $item) :?>
		
		<tr>
			<td><?php echo $item->id;?></td>
			<td><?php echo $item->name;?></td>
			<td><?php echo $item->cname;?></td>
			<td><?php echo $item->description;?></td>
			<td><a href="/references/list/id/<?php echo $item->id;?>">Valores de referencia</a></td>
			<td align="center"><a  class="btn btn-success" href="/items/update/id/<?php echo $item->id ?>"><i class="icon-pencil icon-white"></i></a></td>
			<td align="center"><a  class="btn btn-danger"  href="/items/delete/id/<?php echo $item->id ?>"><i class="icon-trash icon-white"></i></a></td>
		</tr>
		
	
		<?php endforeach;?>
		<?php else : ?>
		<tr>
			<td colspan="7">No hay datos</td>
		</tr>
		
		<?php endif;?>
		
		
		<?php if( count( $this->paginator )):?>
		    <?php echo $this->paginator;?>
		<?php endif;?>
	</table>

 