
<div class="page-header">
<h3>Listado de Analisis</h3>

</div>
<form class="well form-search"><input type="text"
	class="input-medium search-query" placeholder="Nombre Solicitante"> <input
	class="input-medium" value="02-16-2012" id="dp1"  readonly="readonly" type="text"> <span
	class="add-on"><i class="icon-th"></i></span> <input
	class="input-medium" size="16" value="12-02-2012" readonly="readonly"
	type="text"> <span class="add-on"><i class="icon-th"></i></span>
<button type="submit" class="btn btn-info"><i
	class="icon-search icon-white"></i> Buscar</button>
<a class="btn btn-success" href="/analysis/add/"><i
	class="icon-plus-sign icon-white"></i> Agregar</a></form>
