<div class="span" id="nota_remision">
<div class="page-header">
<h3 style="text-align:center">PROMOSERVICIOS DE SALUD S.A. DE C.V.<br>
<small>
<address>

        <strong>Botica San Juan
        Calle Sur 15 No. 489
        Orizaba, Ver</strong> <br>
        Tel:  (272)72 5 42 69     
</address>
</small></h3>
</div>

<table class="table table-condensed">
	<thead>
		<tr>
			<td></td>
			<td></td>
			<td>FECHA:</td>
			<td><?php echo date("d-m-Y", strtotime($this->data['date_entered']));?></td>

		</tr>
		<tr>
			<td>Nombre:</td>
			<td><?php echo $this->paciente; ?></td>
			<td>FOLIO:</td>
			<td><?php echo $this->data['id']; ?></td>

		</tr>


	</thead>

</table>

<table class="table table-striped">
	<tbody>
		<tr>
			<th>Cant.</th>
			<th>Nombre de Examen</th>
			<th>Unidad</th>

			<th>P. Unit.</th>
			<!--<th>Descripci&oacute;n</th>
			 <th>Descuento</th> -->
			<th>Importe</th>

		</tr>
		<?php $i =1;?>
		<?php foreach( $this->paginator as $test) :?>

		<tr>
			<td><?php echo $i++;?></td>
			<td><?php echo $test->name;?></td>
			<td>No Aplica</td>
			<!--<td>GASOMETRIA</td>
			<td>$1000</td>
			<td>10%</td> -->
			<td><?php echo number_format($test->amount,2);?></td>
			<td><?php echo number_format($test->amount,2);?></td>
		</tr>

		<?php endforeach;?>

	</tbody>
</table>
<table class="table table-condensed">

	<tbody>
		<tr>
			<td rowspan="3" colspan="7">Importe con letra: <?php echo $this->letras;?></td>

			<td>Sub total</td>
			<td>$ <?php echo number_format($this->monto,2);  ?></td>
		</tr>
		<tr>

			<td>% Descuento</td>
			<td><?php echo number_format(0,2);  ?> %</td>
		</tr>
		<!-- 
		<tr>


			<td>IVA</td>
			<td>0%</td>
		</tr>
		 -->
		<tr>


			<td>Total</td>
			<td>$ <?php echo number_format($this->monto,2);  ?></td>
		</tr>
	</tbody>
</table>

<div class="" style="text-align:center">
<p>
http://prossalud.com.mx
</p>
</div>

</div>

<p><a class="btn btn-success"
	href="javascript:imprSelec('nota_remision')"><i
	class="icon-print  icon-white"></i> Imprimir</a></p>
