<div class="row-fluid alert">
<div class="span8">
<div class="alert" style=" font-family: Arial; color:#000000;">
<h2>PROMOSERVICIOS DE SALUD S.A. DE C.V.</h2>
</div>

<table class="table alert" >
	<thead>
		<tr>
			<th colspan="2">NOTA DE REMISION</th>
			<th>Fecha:</th>
			<td>2012-07-27</td>
			<th>FOLIO:</th>
			<td>2012-07-27</td>

		</tr>
	</thead>

</table>
</div>
<div class="span4 alert" style=" font-family: Arial; color:#000000;" >
         <address>
        <strong>Calle Sur 15 No. 489</strong><br>
        Orizaba, Ver.<br>
        01 272 72 5 42 69<br>
        prosalud2012@hotmail.com
      </address>
       
</div>



 
<div class="row-fluid show-grid">
<div class="span12 ">
 <table class="table table-condensed alert" style=" font-family: Arial; color:#000000;">
	<thead>
		<tr>
			<th>RFC:</th>
			<td colspan="3">PUPC100101EB7</td>
		</tr>
	</thead>
	<tbody>
		<tr>
			<th>Nombre:</th>
			<td colspan="3">Pablo Pedroza Piña</td>

		</tr>
		<tr>
			<th>Direccion:</th>
			<td colspan="3">Ave 20 de Noviembre entre 1 Sur y 4 Sur 2 Col. El
			Espinal</td>

		</tr>
		<tr>
			<th>CP:</th>
			<td>94329</td>
			<th>Ciudad:</th>
			<td>Orizaba</td>
		</tr>
		<tr>
			<th>Estado:</th>
			<td>Veracruz</td>
			<th>Pais:</th>
			<td>Mexico</td>
		</tr>
	</tbody>
</table>
<div class="alert">
<table class="table table-striped table-bordered table-condensed ">
	<thead>
		<tr>
			<th>#</th>
			<th>Cantidad</th>
			<th>Unidad</th>
			<th>Descripcion</th>
			<th>P. Unitario</th>
			<th>Importe</th>

		</tr>
	</thead>
	<tbody>

		<tr>
			<td>1</td>
			<td>Mark</td>
			<td>Otto</td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td>2</td>
			<td>Jacob</td>
			<td>Thornton</td>
			<td>@fat</td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td>1</td>
			<td>Mark</td>
			<td>Otto</td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td>2</td>
			<td>Jacob</td>
			<td>Thornton</td>
			<td>@fat</td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td>1</td>
			<td>Mark</td>
			<td>Otto</td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td>2</td>
			<td>Jacob</td>
			<td>Thornton</td>
			<td>@fat</td>
			<td></td>
			<td></td>
		</tr>

	</tbody>
</table>
</div>
<div class="alert" style=" font-family: Arial; color:#000000;">
<table class="table table-bordered table-condensed">

	<tbody>
		<tr>
			<td rowspan="3" colspan="3">Importe con letra:</td>
			<td>Sub total</td>
			<td>@mdo</td>
		</tr>
		<tr>

			<td>Iva</td>
			<td>@TwBootstrap</td>
		</tr>
		<tr>

			<td>Total</td>
			<td>@TwBootstrap</td>
		</tr>
	</tbody>
</table>
</div>
<div class="alert">
<p align="center">http://prossalud.com.mx/</p>

<p align="center">PROMOSERVICIOS DE SALUD S.A. DE C.V.</p>
</div>
</div>
</div>
</div>



