<div class="well tabbable tabs-left">
<ul class="nav nav-tabs">
    <li class="active"><a href="#rA" data-toggle="tab"><h2>Convenios</h2><p>Trabajamos con tu aseguradora, medico o empresa!</p></a></li>
	<li><a href="#rB" data-toggle="tab"><h2>Pacientes</h2><p>Consulta tus resultados en linea!</p></a></li>
	<li><a href="#rC" data-toggle="tab"><h2>Promociones</h2><p>Mantenemos un expediente!</p></a></li>
</ul>
<div class="tab-content">

<div class="tab-pane active" id="rA">
<div class="hero-unit" style="background-color: transparent;
background-image: url('https://kippt-static.s3.amazonaws.com/img/bg-home.jpg');
background-repeat: no-repeat;
background-attachment: scroll;">
<h1 style="color: #000;">Empresas</h1>
<p style="color: #000;">Convenios con medicos, hospitales, empresas y aseguradoras Recibe nuestras promociones y paquetes por correo electrónico.</p>
<p><a class="btn btn-info btn-large ">leer mas &raquo;</a></p>
</div></div>
<div class="tab-pane" id="rB">
<div class="hero-unit" style="background-color: transparent;
background-image: url('https://kippt-static.s3.amazonaws.com/img/bg-home.jpg');
background-repeat: no-repeat;
background-attachment: scroll;">
<h1 style="color: #000;">Pacientes</h1>
<p style="color: #000;">Mantenemos un historia clínico básica para conocer los
antecedentes y de alguna forma, valorar el riesgos.</p>
<p><a class="btn btn-info btn-large ">leer mas &raquo;</a></p>
</div></div>
<div class="tab-pane" id="rC">
<div class="hero-unit" style="background-color: transparent;
background-image: url('https://kippt-static.s3.amazonaws.com/img/bg-home.jpg');
background-repeat: no-repeat;
background-attachment: scroll;">
<h1 style="color: #000;">Promociones</h1>
<p style="color: #000;">
Recibe nuestras promociones y paquetes por correo electrónico.
Suscríbete a nuestra lista ...</p>
<p><a class="btn btn-info btn-large ">leer mas &raquo;</a></p>
</div></div>
 
</div>
</div>	
<div id="myCarousel" class="carousel slide">
<!-- Carousel items -->
<div class="carousel-inner">
<div class="active item">
        <ul class="thumbnails">
<li class="span3"><a href="#" class="thumbnail"> <img
src="/img/DSC_0283.jpg" alt="" width="260px" height="146px"> </a></li>
<li class="span3"><a href="#" class="thumbnail"> <img
src="/img/DSC_0289.jpg" alt="" width="260px" height="146px"> </a></li>

			<li class="span3"><a href="#" class="thumbnail"> <img
src="/img/DSC00810.jpg" alt=""> </a></li>
<li class="span3"><a href="#" class="thumbnail"> <img
src="/img/DSC00811.jpg" alt=""> </a></li>
</ul>
 </div>
<div class="item">
    <ul class="thumbnails">
<li class="span3"><a href="#" class="thumbnail"> <img src="/img/DSC00791.jpg" alt="" > </a></li>
<li class="span3"><a href="#" class="thumbnail"> <img
src="/img/DSC00799.jpg" alt=""> </a></li>
<li class="span3"><a href="#" class="thumbnail"> <img
src="/img/DSC_0288.jpg" alt="" width="260px" height="146px"> </a></li>
<li class="span3"><a href="#" class="thumbnail"> <img
src="/img/DSC_0287.jpg" alt="" width="260px" height="146px"> </a></li>
</ul>
</div>
</div>
<!-- Carousel nav -->
<a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
<a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div>
 